---

- repo: local
  hooks:
    - id: config
      name: config
      entry: docker-compose -f docker-compose.yml -f docker/docker-compose.prod.yml config --quiet
      pass_filenames: false
      language: system
    - id: qa
      name: qa
      entry: docker-compose run -e INSIDE_CI=0 web sh ./docker/ci.sh
      pass_filenames: false
      language: system
    - id: yamllint
      name: yamllint
      description: This hook runs yamllint.
      entry: pipenv run yamllint .yamllint-light .
      pass_filenames: false
      language: system
      types: [yaml]
